#Êý¾Ý¿â
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lawers?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: KevinHikariPool
      maximum-pool-size: 100
      connection-timeout: 60000
      minimum-idle: 10
      max-lifetime: 540000
      connection-test-query: SELECT 1
server:
  port: 8989